---
micronaut:
  application:
    name: test-data-mn

jackson:
  bean-introspection-module: true

---
#datasources.default: {}

datasources:
  default:
    url: jdbc:h2:mem:devDb;INIT=RUNSCRIPT FROM 'classpath:schema.sql'
    driverClassName: org.h2.Driver
    username: sa
    password: ''
#    schema-generate: CREATE_DROP
    dialect: H2